### ISSUE TITLE
I used neyha mod. That mod just totally makes the window impossible to use. can u pls tell me how can i change the mod from the game files coz it is impossible to do in game

### ISSUE THREAD

**Issue by HIPPOPOTOMUS** [LaFClient/LaF#31]
One of discord trolls recommended me to use Neyha mod. It just makes the screen go RGB Colours and nothing works and u can hear a sound of a man crying. can u pls help me to tell how to disable the mod from game files. appreciate it

**Comment by CommanderAnime** [comment]
@HIPPOPOTOMUS F12 > Console
Copy
```javascript
localStorage.setItem('krk_lastMod', '');
```
into the console and press enter. Relaunch the client.  
That should do the trick.

**Comment by HIPPOPOTOMUS** [comment]
UwU

**Comment by CommanderAnime** [comment]
@HIPPOPOTOMUS or @Hiro527 please close issue
